version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: bumang_blog_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: bumang_blog_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: bumang_blog_db
    restart: always
    ports:
      - '5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: bumang/bumang-blog-backend:latest
    container_name: bumang_blog_backend
    restart: unless-stopped
    ports:
      - '3000'
    depends_on:
      - db
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
